db:
  image: postgres
  volumes:
    - ./data/pg:/var/lib/postgresql
  ports:
    - "5432:5432"
redis:
  image: redis
web:
  extends: 
    file: docker-compose.web.yml
    service: web
  links:
    - db
    - redis