web:
  extends: 
    file: docker-compose.web.yml
    service: web
  links:
    - db
    - redis
db:
  image: postgres
  volumes:
    - ./data/pg:/var/lib/postgresql
  ports:
    - "5432:5432"
redis:
  image: redis
  volumes: 
    - ./data/redis:/data
    - ./redis.production.conf:/redis.production.conf
  # command: redis-server /redis.production.conf
